disabled_rules: # rule identifiers to exclude from running
  - comma
  - file_length
  - function_body_length
  - identifier_name
  - opening_brace
  - trailing_comma
  - type_body_length
excluded: # paths to ignore during linting
  - .build
